### ISSUE TITLE
Json data API problem

### ISSUE THREAD

**Issue by pratikwayal01** [pratikwayal01/Food-api#1]
During creating api all the json values having the space separated keyys are balnk , have deploy the api on render by my same repo and here everything is fine but at the api its balnk . therefore having issue in fetching data to front end .
![Screenshot 2024-09-10 125102](https://github.com/user-attachments/assets/2a4b1bb6-0014-4aef-a81a-549db0e4f450)
![Screenshot 2024-09-10 124807](https://github.com/user-attachments/assets/f80345b7-f072-43de-81f1-c3c048826355)

**Comment by ahmarcode** [comment]
[foodData.json](https://github.com/user-attachments/files/16944191/foodData.json)
Add "-" in name property, readability of json-server scritps (hosting of api)
